all:
	gcc -Wall --pedantic src/*.c -o bin/gauss

test1: all
	bin/gauss dane/A dane/b

test2: all 
	bin/gauss dane/C dane/d

test3: all
	bin/gauss dane/E dane/f

test4: all 
	bin/gauss dane/G dane/h

test5: all
	bin/gauss dane/I dane/j
